version: "2"
services:
  jumphost:
    build: .
    environment:
      KNOCK_SEQUENCE: ${KNOCK_SEQUENCE}
      PUBLIC_KEYS_REPO: /data/public-keys
      # AUTO_CREATE_USERS: 1
    restart: always
    network_mode: "host"
    privileged: true
    volumes:
      - "./data/:/data"
